# Generated by Django 3.1.2 on 2021-10-05 15:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentModel',
            fields=[
                ('Agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataJoined', models.CharField(default=datetime.datetime(2021, 10, 5, 17, 50, 56, 559717), max_length=100)),
                ('Agent_Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficialModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('female', 'female')], max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hospitalModel',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PharomacyModel',
            fields=[
                ('Pharmacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('PharmacyName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransferModels',
            fields=[
                ('Transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('transferName', models.CharField(max_length=100)),
                ('deases', models.CharField(max_length=100)),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.agentmodel')),
                ('Beneficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.beneficialmodel')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.hospitalmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PharomacyCertificate',
            fields=[
                ('certID', models.AutoField(primary_key=True, serialize=False)),
                ('certTitle', models.CharField(default='Pharomacy Certificate of merits For FARG  Beneficial ', editable=False, max_length=100)),
                ('certDate', models.CharField(default=datetime.datetime(2021, 10, 5, 17, 50, 56, 559717), max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('drungDetails', models.TextField()),
                ('Beneficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.beneficialmodel')),
                ('Pharomacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.pharomacymodel')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.agentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='pharmacistModel',
            fields=[
                ('pharmacist_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataJoined', models.CharField(default=datetime.datetime(2021, 10, 5, 17, 50, 56, 559717), max_length=100)),
                ('Pharomacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.pharomacymodel')),
                ('pharmacist_Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hospitalCertificate',
            fields=[
                ('certID', models.AutoField(primary_key=True, serialize=False)),
                ('certTitle', models.CharField(default='hospital Certificate of merits For FARG  Beneficial ', editable=False, max_length=100)),
                ('certDate', models.CharField(default=datetime.datetime(2021, 10, 5, 17, 50, 56, 559717), max_length=100)),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.agentmodel')),
                ('Beneficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.beneficialmodel')),
                ('TransiderName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.transfermodels')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.hospitalmodel')),
            ],
        ),
        migrations.AddField(
            model_name='agentmodel',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.hospitalmodel'),
        ),
    ]
