# Generated by Django 3.1.2 on 2021-10-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FARGApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficialmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('female', 'female')], max_length=100),
        ),
    ]
