# Generated by Django 3.1.2 on 2021-10-01 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FARGApp', '0002_auto_20211001_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalModel',
            fields=[
                ('hospital_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AgentModel',
            fields=[
                ('Agent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agent_userName', models.CharField(max_length=100)),
                ('dataJoined', models.DateTimeField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.hospitalmodel')),
            ],
        ),
    ]
