# Generated by Django 3.1.2 on 2021-10-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FARGApp', '0003_agentmodel_hospitalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharomacyModel',
            fields=[
                ('Pharmacy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('addressName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
