# Generated by Django 3.1.2 on 2021-10-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FARGApp', '0004_pharomacymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharomacymodel',
            old_name='addressName',
            new_name='PharmacyName',
        ),
    ]
