# Generated by Django 3.1.2 on 2021-10-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FARGApp', '0006_transfermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferModel2',
            fields=[
                ('Transfer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.agentmodel')),
                ('Beneficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.beneficialmodel')),
                ('hospital', models.ForeignKey(db_column='hospital_name', on_delete=django.db.models.deletion.CASCADE, to='FARGApp.hospitalmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='TransferModel',
        ),
    ]
