# Generated by Django 3.1.2 on 2021-10-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FARGApp', '0007_auto_20211001_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugIswing',
            fields=[
                ('DrugID', models.IntegerField(primary_key=True, serialize=False)),
                ('Pharomacist_name', models.CharField(max_length=100)),
                ('DrugDetails', models.CharField(max_length=100)),
                ('Beneficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.beneficialmodel')),
                ('Pharomacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.pharomacymodel')),
            ],
        ),
    ]
