# Generated by Django 3.1.2 on 2021-10-02 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FARGApp', '0008_drugiswing'),
    ]

    operations = [
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('fristName', models.CharField(max_length=100)),
                ('lastNname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='locationmodel',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('fristName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ristName', to='FARGApp.testmodel')),
            ],
        ),
    ]
