# Generated by Django 3.1.2 on 2021-10-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FARGApp', '0009_locationmodel_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugIswingmodel',
            fields=[
                ('DrugID', models.IntegerField(primary_key=True, serialize=False)),
                ('Pharomacist_name', models.CharField(max_length=100)),
                ('DrugDetails', models.CharField(max_length=100)),
                ('drungPrice', models.CharField(max_length=100)),
                ('DrugName', models.CharField(max_length=100)),
                ('Beneficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.beneficialmodel')),
                ('Pharomacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.pharomacymodel')),
            ],
        ),
        migrations.CreateModel(
            name='TransferModels',
            fields=[
                ('Transfer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transferName', models.CharField(max_length=100)),
                ('deases', models.CharField(max_length=100)),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.agentmodel')),
                ('Beneficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.beneficialmodel')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.hospitalmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='fristName',
        ),
        migrations.RemoveField(
            model_name='transfermodel2',
            name='Agent',
        ),
        migrations.RemoveField(
            model_name='transfermodel2',
            name='Beneficial',
        ),
        migrations.RemoveField(
            model_name='transfermodel2',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='DrugIswing',
        ),
        migrations.DeleteModel(
            name='locationmodel',
        ),
        migrations.DeleteModel(
            name='testModel',
        ),
        migrations.DeleteModel(
            name='TransferModel2',
        ),
    ]
