# Generated by Django 3.1.2 on 2021-10-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FARGApp', '0010_auto_20211002_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugiswingmodel',
            name='DrugDetails',
            field=models.TextField(),
        ),
    ]
