# Generated by Django 3.1.2 on 2021-10-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FARGApp', '0012_certificatetransfer_pharomacytransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharomacyTransfer2',
            fields=[
                ('certID', models.IntegerField(primary_key=True, serialize=False)),
                ('certDate', models.DateTimeField()),
                ('Beneficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.beneficialmodel')),
                ('Pharomacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.pharomacymodel')),
                ('TransiderName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.transfermodels')),
                ('certTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.certificatetransfer')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.drugiswingmodel')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FARGApp.agentmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='PharomacyTransfer',
        ),
    ]
